"""Add wallet pass tables

Revision ID: wallet_pass_tables
Revises: 50f0433c70a4
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'wallet_pass_tables'
down_revision = '50f0433c70a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_passes',
    sa.Column('pass_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('pass_type', sa.String(), nullable=False),
    sa.Column('pass_class', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('pass_data', sa.String(), nullable=False),
    sa.Column('pass_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('pass_id')
    )
    op.create_index(op.f('ix_wallet_passes_pass_id'), 'wallet_passes', ['pass_id'], unique=False)
    op.create_index(op.f('ix_wallet_passes_serial_number'), 'wallet_passes', ['serial_number'], unique=True)
    op.create_index(op.f('ix_wallet_passes_user_id'), 'wallet_passes', ['user_id'], unique=False)
    
    op.create_table('wallet_pass_templates',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('pass_type', sa.String(), nullable=False),
    sa.Column('pass_class', sa.String(), nullable=False),
    sa.Column('template_data', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index(op.f('ix_wallet_pass_templates_template_id'), 'wallet_pass_templates', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_pass_templates_template_id'), table_name='wallet_pass_templates')
    op.drop_table('wallet_pass_templates')
    op.drop_index(op.f('ix_wallet_passes_user_id'), table_name='wallet_passes')
    op.drop_index(op.f('ix_wallet_passes_serial_number'), table_name='wallet_passes')
    op.drop_index(op.f('ix_wallet_passes_pass_id'), table_name='wallet_passes')
    op.drop_table('wallet_passes')
    # ### end Alembic commands ###
